# Data cleaning and summarizing with dplyr

## The United Nations voting dataset

### UN Voting Dataset

* Descrption
    - rcid: Roll call ID
    - session: Session(year). Sessions for alternating years are included to keep the size of dataset reasonable
    - vote: Vote, 1(yes), 9(the country was not a member of UN yet)
    - ccode: Country code
    
### Votes in dplyr

In [8]:
# Load dplyr package
library(dplyr)
library(data.table)

# Load the UN voting dataset
votes <- readRDS("./14_exploratory_data_analysis_in_r_case_study/votes.rds")

# Check the data set
head(votes, n = 10)

   rcid session vote ccode
1  46   2       1     2
2  46   2       1    20
3  46   2       9    31
4  46   2       1    40
5  46   2       1    41
6  46   2       1    42
7  46   2       9    51
8  46   2       9    52
9  46   2       9    53
10 46   2       9    54

### dplyr verbs

* filter(): Subsets observations from the data set to remove rows that are not interested
* mutate(): Adds variables or changes existing variables

### original data

* vote
    - 1 = Yes
    - 2 = Abstain
    - 3 = No
    - 8 = Not present: Not interested
    - 9 = Not a member: Not interested

### Filtering rows

The vote column in the dataset has a number that represents that country's vote:

* 1 = Yes
* 2 = Abstain
* 3 = No
* 8 = Not present
* 9 = Not a member

One step of data cleaning is removing observations (rows) that you're not interested in. In this case, you want to remove "Not present" and "Not a member".

INSTRUCTIONS

* Load the dplyr package.
* Print the votes table.
* Filter out rows where the vote recorded is "not present" or "not a member", leaving cases where it is "yes", "abstain", or "no".

In [13]:
# Load the dplyr package
library(dplyr)

# Print the votes dataset
print(votes)

# Filter for votes that are "yes", "abstain", or "no"
votes %>%
    filter(vote <= 3)

# A tibble: 508,929 x 4
    rcid session  vote ccode
   <dbl>   <dbl> <dbl> <int>
 1  46.0    2.00  1.00     2
 2  46.0    2.00  1.00    20
 3  46.0    2.00  9.00    31
 4  46.0    2.00  1.00    40
 5  46.0    2.00  1.00    41
 6  46.0    2.00  1.00    42
 7  46.0    2.00  9.00    51
 8  46.0    2.00  9.00    52
 9  46.0    2.00  9.00    53
10  46.0    2.00  9.00    54
# ... with 508,919 more rows

       rcid session vote ccode
1      46   2       1      2
2      46   2       1     20
3      46   2       1     40
4      46   2       1     41
5      46   2       1     42
6      46   2       1     70
7      46   2       1     90
8      46   2       1     91
9      46   2       1     92
10     46   2       1     93
11     46   2       1     94
12     46   2       1     95
13     46   2       1    100
14     46   2       1    101
15     46   2       1    130
16     46   2       1    135
17     46   2       1    140
18     46   2       1    150
19     46   2       1    155
20     46   2       1    160
21     46   2       1    165
22     46   2       1    200
23     46   2       1    210
24     46   2       1    211
25     46   2       1    212
26     46   2       1    220
27     46   2       3    290
28     46   2       3    315
29     46   2       3    345
30     46   2       1    350
...    ...  ...     ...  ...
353518 9056 22      3    616
353519 9056 22      3    620
353520 9056 22      3    625
353521 9056 22      2    630
353522 9056 22      2    640
353523 9056 22      3    645
353524 9056 22      3    651
353525 9056 22      3    652
353526 9056 22      3    660
353527 9056 22      3    663
353528 9056 22      2    666
353529 9056 22      3    670
353530 9056 22      3    678
353531 9056 22      3    690
353532 9056 22      3    700
353533 9056 22      1    712
353534 9056 22      1    713
353535 9056 22      1    740
353536 9056 22      1    750
353537 9056 22      3    770
353538 9056 22      2    780
353539 9056 22      1    790
353540 9056 22      1    800
353541 9056 22      1    812
353542 9056 22      3    820
353543 9056 22      1    830
353544 9056 22      1    840
353545 9056 22      2    850
353546 9056 22      1    900
353547 9056 22      1    920

### Adding a year column

The next step of data cleaning is manipulating your variables (columns) to make them more informative.

In this case, you have a session column that is hard to interpret intuitively. But since the UN started voting in 1946, and holds one session per year, you can get the year of a UN resolution by adding 1945 to the session number.

INSTRUCTIONS

* Use mutate() to add a year column by adding 1945 to the session column.

In [14]:
# Add another %>% step to add a year column
votes %>%
    filter(vote <= 3) %>%
    mutate(year = session + 1945)

       rcid session vote ccode year
1      46   2       1      2   1947
2      46   2       1     20   1947
3      46   2       1     40   1947
4      46   2       1     41   1947
5      46   2       1     42   1947
6      46   2       1     70   1947
7      46   2       1     90   1947
8      46   2       1     91   1947
9      46   2       1     92   1947
10     46   2       1     93   1947
11     46   2       1     94   1947
12     46   2       1     95   1947
13     46   2       1    100   1947
14     46   2       1    101   1947
15     46   2       1    130   1947
16     46   2       1    135   1947
17     46   2       1    140   1947
18     46   2       1    150   1947
19     46   2       1    155   1947
20     46   2       1    160   1947
21     46   2       1    165   1947
22     46   2       1    200   1947
23     46   2       1    210   1947
24     46   2       1    211   1947
25     46   2       1    212   1947
26     46   2       1    220   1947
27     46   2       3    290   1947
28     46   2       3    315   1947
29     46   2       3    345   1947
30     46   2       1    350   1947
...    ...  ...     ...  ...   ...
353518 9056 22      3    616   1967
353519 9056 22      3    620   1967
353520 9056 22      3    625   1967
353521 9056 22      2    630   1967
353522 9056 22      2    640   1967
353523 9056 22      3    645   1967
353524 9056 22      3    651   1967
353525 9056 22      3    652   1967
353526 9056 22      3    660   1967
353527 9056 22      3    663   1967
353528 9056 22      2    666   1967
353529 9056 22      3    670   1967
353530 9056 22      3    678   1967
353531 9056 22      3    690   1967
353532 9056 22      3    700   1967
353533 9056 22      1    712   1967
353534 9056 22      1    713   1967
353535 9056 22      1    740   1967
353536 9056 22      1    750   1967
353537 9056 22      3    770   1967
353538 9056 22      2    780   1967
353539 9056 22      1    790   1967
353540 9056 22      1    800   1967
353541 9056 22      1    812   1967
353542 9056 22      3    820   1967
353543 9056 22      1    830   1967
353544 9056 22      1    840   1967
353545 9056 22      2    850   1967
353546 9056 22      1    900   1967
353547 9056 22      1    920   1967

### Adding a country column

The country codes in the ccode column are what's called Correlates of War codes. This isn't ideal for an analysis, since you'd like to work with recognizable country names.

You can use the countrycode package to translate. For example:
```
library(countrycode)

# Translate the country code 2
> countrycode(2, "cown", "country.name")
[1] "United States"

# Translate multiple country codes
> countrycode(c(2, 20, 40), "cown", "country.name")
[1] "United States" "Canada"        "Cuba"
```

INSTRUCTIONS

* Load the countrycode package.
* Convert the country code 100 to its country name.
* Add a new country column in your mutate() statement containing country names, using the countrycode() function to translate from the ccode column. Save the result to votes_processed.

In [35]:
# Load the countrycode package
library(countrycode)

# Convert country code 100
countrycode(100, "cown", "country.name")

# Add a country column within the mutate: votes_processed
votes_processed <- votes %>%
    filter(vote <= 3) %>%
    mutate(year = session + 1945) %>%
    mutate(country = countrycode(ccode, "cown", "country.name"))

# Fill out NAs
# 260 = "Federal Republic of Germay"
votes_processed[votes_processed$ccode == 260, "country"] <- "Federal Republic of Germany"

# 816 = "Viet Nam"
votes_processed[votes_processed$ccode == 816, "country"] <- "Viet Nam"

[1] "Colombia"

Warning message in countrycode(ccode, "cown", "country.name"):
"Some values were not matched unambiguously: 260, 816
"

## Grouping and summarizing

### Processed votes

* There are more than 350,000 rows in the data set, so it is requred to extract some summary statistics that maybe interested.

### Using "% of Yes Votes" as a summary

* Wheter the country is consesus with the majority of the vote or against it.

### dplyr verb: summarize(summarise)

* summarise() turns many rows into one

```
# summarise: The total number of data, percentage of yes votes
votes_processed %>%
    summarise(total = n(),
              percent_yes = mean(vote = 1)) 
```

### dplyr verb: group_by

* group_by() before summarise() turns groups into one row each.

```
# summarise the number of rows and the percentage of yes by year
votes_processed %>%
    group_by(year) %>%
    summarise(total = n(),
              percent_yes = mean(vote == 1))
```

In [36]:
print(votes_processed)

# A tibble: 353,547 x 6
    rcid session  vote ccode  year country
   <dbl>   <dbl> <dbl> <int> <dbl> <chr>
 1  46.0    2.00  1.00     2  1947 United States
 2  46.0    2.00  1.00    20  1947 Canada
 3  46.0    2.00  1.00    40  1947 Cuba
 4  46.0    2.00  1.00    41  1947 Haiti
 5  46.0    2.00  1.00    42  1947 Dominican Republic
 6  46.0    2.00  1.00    70  1947 Mexico
 7  46.0    2.00  1.00    90  1947 Guatemala
 8  46.0    2.00  1.00    91  1947 Honduras
 9  46.0    2.00  1.00    92  1947 El Salvador
10  46.0    2.00  1.00    93  1947 Nicaragua
# ... with 353,537 more rows

### Summarizing the full dataset

In this analysis, you're going to focus on "% of votes that are yes" as a metric for the "agreeableness" of countries.

You'll start by finding this summary for the entire dataset: the fraction of all votes in their history that were "yes". Note that within your call to summarize(), you can use n() to find the total number of votes and mean(vote == 1) to find the fraction of "yes" votes.

INSTRUCTIONS

* Print the votes_processed dataset that you created in the previous exercise.
* Summarize the dataset using the summarize() function to create two columns:
    - total: with the number of votes
    - percent_yes: the percentage of "yes" votes

In [37]:
# Print votes_processed
print(votes_processed)

# Find total and fraction of "yes" votes
votes_processed %>%
    summarise(total = n(),
               percent_yes = mean(vote == 1))

# A tibble: 353,547 x 6
    rcid session  vote ccode  year country
   <dbl>   <dbl> <dbl> <int> <dbl> <chr>
 1  46.0    2.00  1.00     2  1947 United States
 2  46.0    2.00  1.00    20  1947 Canada
 3  46.0    2.00  1.00    40  1947 Cuba
 4  46.0    2.00  1.00    41  1947 Haiti
 5  46.0    2.00  1.00    42  1947 Dominican Republic
 6  46.0    2.00  1.00    70  1947 Mexico
 7  46.0    2.00  1.00    90  1947 Guatemala
 8  46.0    2.00  1.00    91  1947 Honduras
 9  46.0    2.00  1.00    92  1947 El Salvador
10  46.0    2.00  1.00    93  1947 Nicaragua
# ... with 353,537 more rows

  total  percent_yes
1 353547 0.7999248

### Summarizing by year

The summarize() function is especially useful because it can be used within groups.

For example, you might like to know how much the average "agreeableness" of countries changed from year to year. To examine this, you can use group_by() to perform your summary not for the entire dataset, but within each year.

INSTRUCTIONS

* Add a group_by() to your code to summarize() within each year.

In [38]:
# Change this code to summarize by year
votes_processed %>%
    group_by(year) %>%
    summarize(total = n(),
              percent_yes = mean(vote == 1))

   year total percent_yes
1  1947  2039 0.5693968
2  1949  3469 0.4375901
3  1951  1434 0.5850767
4  1953  1537 0.6317502
5  1955  2169 0.6947902
6  1957  2708 0.6085672
7  1959  4326 0.5880721
8  1961  7482 0.5729751
9  1963  3308 0.7294438
10 1965  4382 0.7078959
11 1967  6446 0.6180577
12 1969  4942 0.6649130
13 1971 14648 0.7142272
14 1973 11521 0.7718948
15 1975  8987 0.8196284
16 1977 13310 0.8736289
17 1979 17103 0.8431854
18 1981 19236 0.8401955
19 1983 21560 0.8491651
20 1985 22775 0.8418441
21 1987 22067 0.8744732
22 1989 17378 0.8830705
23 1991 11357 0.8558598
24 1993 10272 0.7977025
25 1995 12645 0.8094108
26 1997 11106 0.8074914
27 1999 10596 0.8144583
28 2001 10355 0.8117817
29 2003 13099 0.8121994
30 2005 12655 0.8229949
31 2007 13539 0.8107689
32 2009 12112 0.8021797
33 2011 11453 0.8110539
34 2013 11531 0.8070419

### Summarizing by country

In the last exercise, you performed a summary of the votes within each year. You could instead summarize() within each country, which would let you compare voting patterns between countries.

INSTRUCTIONS

* Change the code in the editor to summarize() within each country rather than within each year. Save the result as by_country.

In [40]:
# Summarize by country: by_country
by_country <- 
    votes_processed %>%
    group_by(country) %>%
    summarize(total = n(),
              percent_yes = mean(vote == 1))

by_country

    country                 total percent_yes
1   Afghanistan             2373  0.8592499
2   Albania                 1695  0.7174041
3   Algeria                 2213  0.8992318
4   Andorra                  719  0.6383866
5   Angola                  1431  0.9238295
6   Antigua & Barbuda       1302  0.9124424
7   Argentina               2553  0.7677242
8   Armenia                  758  0.7467018
9   Australia               2575  0.5565049
10  Austria                 2389  0.6224362
11  Azerbaijan               704  0.8622159
12  Bahamas                 1781  0.8944413
13  Bahrain                 2010  0.9348259
14  Bangladesh              1799  0.9444136
15  Barbados                2001  0.9055472
16  Belarus                 2534  0.7600631
17  Belgium                 2568  0.4922118
18  Belize                  1111  0.9270927
19  Benin                   2169  0.9059474
20  Bhutan                  1839  0.9178902
21  Bolivia                 2396  0.8555927
22  Bosnia & Herzegovina     556  0.6762590
23  Botswana                1903  0.9238045
24  Brazil                  2560  0.8144531
25  Brunei                  1247  0.9286287
26  Bulgaria                2377  0.6979386
27  Burkina Faso            2156  0.9086271
28  Burundi                 1935  0.9235142
29  Cambodia                1785  0.8941176
30  Cameroon                2212  0.8521700
... ...                     ...   ...
171 Syria                   2409  0.8509755
172 Taiwan                   534  0.5880150
173 Tajikistan               543  0.8360958
174 Tanzania                2159  0.9152385
175 Thailand                2534  0.8547751
176 Timor-Leste              326  0.9570552
177 Togo                    2260  0.9030973
178 Tonga                    381  0.7427822
179 Trinidad & Tobago       2116  0.9229679
180 Tunisia                 2356  0.9104414
181 Turkey                  2532  0.6986572
182 Turkmenistan             462  0.9047619
183 Tuvalu                   272  0.8198529
184 Uganda                  2045  0.8982885
185 Ukraine                 2570  0.7284047
186 United Arab Emirates    1934  0.9467425
187 United Kingdom          2558  0.4167318
188 United States           2568  0.2694704
189 Uruguay                 2493  0.8150822
190 Uzbekistan               452  0.7566372
191 Vanuatu                 1018  0.9047151
192 Venezuela               2564  0.8553042
193 Viet Nam                1628  0.9090909
194 Yemen                    784  0.9464286
195 Yemen Arab Republic     1572  0.8441476
196 Yemen People's Republic 1209  0.8990902
197 Yugoslavia              2286  0.8258968
198 Zambia                  2123  0.9274611
199 Zanzibar                   2  0.0000000
200 Zimbabwe                1361  0.9493020

## Sorting and filtering summarized data

### by_country dataset

In [41]:
print(by_country)

# A tibble: 200 x 3
   country           total percent_yes
   <chr>             <int>       <dbl>
 1 Afghanistan        2373       0.859
 2 Albania            1695       0.717
 3 Algeria            2213       0.899
 4 Andorra             719       0.638
 5 Angola             1431       0.924
 6 Antigua & Barbuda  1302       0.912
 7 Argentina          2553       0.768
 8 Armenia             758       0.747
 9 Australia          2575       0.557
10 Austria            2389       0.622
# ... with 190 more rows

### dplyr verb: arrange()

* arrange(): Sorts a table based on a variable

```
# Sort the data by ascending order of percent_yes
by_country %>%
    arrange(percent_yes)
```

### Transforming tidy data

* filter()
* group_by()
* summarise()
* arrange()

### Sorting by percentage of "yes" votes

Now that you've summarized the dataset by country, you can start examining it and answering interesting questions.

For example, you might be especially interested in the countries that voted "yes" least often, or the ones that voted "yes" most often.

INSTRUCTIONS

* Print the by_country dataset created in the last exercise.
* Use arrange() to sort the countries in ascending order of percent_yes.
* Arrange the countries by the same variable, but in descending order.

In [42]:
# You have the votes summarized by country
by_country <- votes_processed %>%
    group_by(country) %>%
    summarize(total = n(),
              percent_yes = mean(vote == 1))

# Print the by_country dataset
print(by_country)

# Sort in ascending order of percent_yes
by_country %>%
    arrange(percent_yes)

# Now sort in descending order
by_country %>%
    arrange(desc(percent_yes))

# A tibble: 200 x 3
   country           total percent_yes
   <chr>             <int>       <dbl>
 1 Afghanistan        2373       0.859
 2 Albania            1695       0.717
 3 Algeria            2213       0.899
 4 Andorra             719       0.638
 5 Angola             1431       0.924
 6 Antigua & Barbuda  1302       0.912
 7 Argentina          2553       0.768
 8 Armenia             758       0.747
 9 Australia          2575       0.557
10 Austria            2389       0.622
# ... with 190 more rows

    country                          total percent_yes
1   Zanzibar                            2  0.0000000
2   United States                    2568  0.2694704
3   Palau                             369  0.3387534
4   Israel                           2380  0.3407563
5   Federal Republic of Germany      1075  0.3972093
6   United Kingdom                   2558  0.4167318
7   France                           2527  0.4265928
8   Micronesia (Federated States of)  724  0.4419890
9   Marshall Islands                  757  0.4914135
10  Belgium                          2568  0.4922118
11  Canada                           2576  0.5081522
12  Luxembourg                       2541  0.5120031
13  Italy                            2382  0.5146935
14  Netherlands                      2576  0.5221273
15  Portugal                         2337  0.5241763
16  Australia                        2575  0.5565049
17  Georgia                           713  0.5694250
18  Denmark                          2576  0.5733696
19  Nauru                             251  0.5816733
20  Norway                           2570  0.5821012
21  Japan                            2384  0.5876678
22  Taiwan                            534  0.5880150
23  Latvia                            809  0.5945612
24  Iceland                          2487  0.6003217
25  Germany                           846  0.6016548
26  New Zealand                      2569  0.6076294
27  Lithuania                         836  0.6124402
28  Estonia                           816  0.6151961
29  Moldova                           745  0.6161074
30  Sweden                           2576  0.6164596
... ...                              ...   ...
171 Eritrea                           638  0.9200627
172 Trinidad & Tobago                2116  0.9229679
173 Burundi                          1935  0.9235142
174 Botswana                         1903  0.9238045
175 Angola                           1431  0.9238295
176 Namibia                           792  0.9255051
177 Belize                           1111  0.9270927
178 Zambia                           2123  0.9274611
179 Gambia                           1404  0.9280627
180 Brunei                           1247  0.9286287
181 Guyana                           2071  0.9314341
182 Kuwait                           2152  0.9316914
183 Cape Verde                       1632  0.9332108
184 Oman                             1948  0.9332649
185 Bahrain                          2010  0.9348259
186 Qatar                            2001  0.9370315
187 Suriname                         1635  0.9376147
188 Maldives                         1847  0.9415268
189 Bangladesh                       1799  0.9444136
190 Yemen                             784  0.9464286
191 Mozambique                       1701  0.9465021
192 United Arab Emirates             1934  0.9467425
193 Comoros                          1133  0.9470432
194 Zimbabwe                         1361  0.9493020
195 Mauritius                        1831  0.9497542
196 Timor-Leste                       326  0.9570552
197 Guinea-Bissau                    1538  0.9603381
198 Djibouti                         1598  0.9612015
199 Seychelles                        881  0.9750284
200 São Tomé & Príncipe              1091  0.9761687

    country                          total percent_yes
1   São Tomé & Príncipe              1091  0.9761687
2   Seychelles                        881  0.9750284
3   Djibouti                         1598  0.9612015
4   Guinea-Bissau                    1538  0.9603381
5   Timor-Leste                       326  0.9570552
6   Mauritius                        1831  0.9497542
7   Zimbabwe                         1361  0.9493020
8   Comoros                          1133  0.9470432
9   United Arab Emirates             1934  0.9467425
10  Mozambique                       1701  0.9465021
11  Yemen                             784  0.9464286
12  Bangladesh                       1799  0.9444136
13  Maldives                         1847  0.9415268
14  Suriname                         1635  0.9376147
15  Qatar                            2001  0.9370315
16  Bahrain                          2010  0.9348259
17  Oman                             1948  0.9332649
18  Cape Verde                       1632  0.9332108
19  Kuwait                           2152  0.9316914
20  Guyana                           2071  0.9314341
21  Brunei                           1247  0.9286287
22  Gambia                           1404  0.9280627
23  Zambia                           2123  0.9274611
24  Belize                           1111  0.9270927
25  Namibia                           792  0.9255051
26  Angola                           1431  0.9238295
27  Botswana                         1903  0.9238045
28  Burundi                          1935  0.9235142
29  Trinidad & Tobago                2116  0.9229679
30  Eritrea                           638  0.9200627
... ...                              ...   ...
171 Sweden                           2576  0.6164596
172 Moldova                           745  0.6161074
173 Estonia                           816  0.6151961
174 Lithuania                         836  0.6124402
175 New Zealand                      2569  0.6076294
176 Germany                           846  0.6016548
177 Iceland                          2487  0.6003217
178 Latvia                            809  0.5945612
179 Taiwan                            534  0.5880150
180 Japan                            2384  0.5876678
181 Norway                           2570  0.5821012
182 Nauru                             251  0.5816733
183 Denmark                          2576  0.5733696
184 Georgia                           713  0.5694250
185 Australia                        2575  0.5565049
186 Portugal                         2337  0.5241763
187 Netherlands                      2576  0.5221273
188 Italy                            2382  0.5146935
189 Luxembourg                       2541  0.5120031
190 Canada                           2576  0.5081522
191 Belgium                          2568  0.4922118
192 Marshall Islands                  757  0.4914135
193 Micronesia (Federated States of)  724  0.4419890
194 France                           2527  0.4265928
195 United Kingdom                   2558  0.4167318
196 Federal Republic of Germany      1075  0.3972093
197 Israel                           2380  0.3407563
198 Palau                             369  0.3387534
199 United States                    2568  0.2694704
200 Zanzibar                            2  0.0000000

### Filtering summarized output

In the last exercise, you may have noticed that the country that voted least frequently, Zanzibar, had only 2 votes in the entire dataset. You certainly can't make any substantial conclusions based on that data!

Typically in a progressive analysis, when you find that a few of your observations have very little data while others have plenty, you set some threshold to filter them out.

INSTRUCTIONS

* Use filter() to remove from the sorted data countries that have fewer than 100 votes.

In [43]:
# Filter out countries with fewer than 100 votes
by_country %>%
    filter(total >= 100) %>%
    arrange(percent_yes)

    country                          total percent_yes
1   United States                    2568  0.2694704
2   Palau                             369  0.3387534
3   Israel                           2380  0.3407563
4   Federal Republic of Germany      1075  0.3972093
5   United Kingdom                   2558  0.4167318
6   France                           2527  0.4265928
7   Micronesia (Federated States of)  724  0.4419890
8   Marshall Islands                  757  0.4914135
9   Belgium                          2568  0.4922118
10  Canada                           2576  0.5081522
11  Luxembourg                       2541  0.5120031
12  Italy                            2382  0.5146935
13  Netherlands                      2576  0.5221273
14  Portugal                         2337  0.5241763
15  Australia                        2575  0.5565049
16  Georgia                           713  0.5694250
17  Denmark                          2576  0.5733696
18  Nauru                             251  0.5816733
19  Norway                           2570  0.5821012
20  Japan                            2384  0.5876678
21  Taiwan                            534  0.5880150
22  Latvia                            809  0.5945612
23  Iceland                          2487  0.6003217
24  Germany                           846  0.6016548
25  New Zealand                      2569  0.6076294
26  Lithuania                         836  0.6124402
27  Estonia                           816  0.6151961
28  Moldova                           745  0.6161074
29  Sweden                           2576  0.6164596
30  Czechia                           772  0.6165803
... ...                              ...   ...
168 Eritrea                           638  0.9200627
169 Trinidad & Tobago                2116  0.9229679
170 Burundi                          1935  0.9235142
171 Botswana                         1903  0.9238045
172 Angola                           1431  0.9238295
173 Namibia                           792  0.9255051
174 Belize                           1111  0.9270927
175 Zambia                           2123  0.9274611
176 Gambia                           1404  0.9280627
177 Brunei                           1247  0.9286287
178 Guyana                           2071  0.9314341
179 Kuwait                           2152  0.9316914
180 Cape Verde                       1632  0.9332108
181 Oman                             1948  0.9332649
182 Bahrain                          2010  0.9348259
183 Qatar                            2001  0.9370315
184 Suriname                         1635  0.9376147
185 Maldives                         1847  0.9415268
186 Bangladesh                       1799  0.9444136
187 Yemen                             784  0.9464286
188 Mozambique                       1701  0.9465021
189 United Arab Emirates             1934  0.9467425
190 Comoros                          1133  0.9470432
191 Zimbabwe                         1361  0.9493020
192 Mauritius                        1831  0.9497542
193 Timor-Leste                       326  0.9570552
194 Guinea-Bissau                    1538  0.9603381
195 Djibouti                         1598  0.9612015
196 Seychelles                        881  0.9750284
197 São Tomé & Príncipe              1091  0.9761687